# Generated by Django 3.2.8 on 2021-11-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audan', '0011_auto_20211122_0803'),
        ('users', '0005_auto_20211117_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zhk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='audan.building', verbose_name='Жилой Комплекс'),
        ),
    ]
