# Generated by Django 3.2.8 on 2021-11-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='facility',
            new_name='zhk',
        ),
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_buildings', to='audan.city'),
        ),
    ]
