# Generated by Django 3.2.9 on 2021-12-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audan', '0004_auto_20211221_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Полное описание (Не обязательно)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в тенге (Не обязательно)'),
        ),
    ]
