# Generated by Django 3.2.8 on 2021-11-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audan', '0007_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='audan.city'),
        ),
    ]
