# Generated by Django 3.2.8 on 2021-11-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audan', '0008_alter_building_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
