# Generated by Django 3.2.8 on 2021-11-22 08:03

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('audan', '0010_auto_20211117_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_pics', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='zhk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='audan.building', verbose_name='Жилой Комплекс'),
        ),
    ]
