# Generated by Django 3.2.9 on 2021-11-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audan', '0011_auto_20211122_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='district',
        ),
    ]
